#!/usr/bin/env bash
# Configures ufw to block all incoming traffic except ports 22, 80, and 443

# Install ufw
sudo apt-get update -y
sudo apt-get install -y ufw

# Set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow required ports
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Enable ufw
echo "y" | sudo ufw enable
