#!/usr/bin/env bash
# Configures nginx with a 301 redirect for /redirect_me
apt-get update -y
apt-get install nginx -y

echo "Holberton School" > /var/www/html/index.html

sed -i '/server_name _;/a\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

nginx -s reload 2>/dev/null || service nginx start
